# Generated by Django 5.2.3 on 2025-07-25 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_app', '0004_country_customertype_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('ABSTRACT', 'Abstract Art'), ('SCULPTURE', 'Sculpture'), ('PORTRAIT', 'Portrait Paintings'), ('LANDSCAPE', 'Landscape Paintings'), ('DIGITAL', 'Digital Art'), ('SUPPLIES', 'Painting Supplies'), ('DECAL', 'Wall Decals')], max_length=20),
        ),
    ]
