# Generated by Django 5.2.3 on 2025-06-30 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='img')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('CANVAS', 'Canvas Art'), ('PRINTS', 'Prints'), ('JEWELRY', 'Jewelry'), ('ACCESSORIES', 'Accessories'), ('CRAFT', 'Craft Supplies'), ('GIFT', 'Gift Items'), ('FOR_HER', 'Gift Ideas for Girls'), ('FOR_HIM', 'Gift for Him'), ('FOR_KIDS', 'Gift for Kids'), ('BIRTHDAY', 'Birthday Surprise Boxes'), ('EARRINGS', 'Earrings'), ('HAIR_CLIP', 'Hair Clip'), ('NECKPIECES', 'Neckpieces Set'), ('BAGS', 'Bags'), ('KEYRINGS', 'Key Rings'), ('PAPER_CRAFT', 'Paper Craft DIY Kids')], max_length=15, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_gift_item', models.BooleanField(default=False)),
                ('is_craft_item', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
